# The following variables should be set in the .env file
# datasource - the Docker image for the generic-datasource
# target     - where the generic datasource looks for data
# coref      - data directory for the coref corpus
# reference  - same as above
# protein    - same as above
# semeval    - same as above

version: "3"

services:
    registry:
      image: registry:2
      ports:
        - 127.0.0.1:8500:5000
      environment:
        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      volumes:
        - /var/lib/docker:/data
      deploy:
        replicas: 1
    coref:
      image: lappsgrid/generic-datasource:latest
      ports:
        - 8080:8080
      volumes:
        - /var/lib/corora/BIONLP2016/bionlp-st-ge-2016-coref:/var/lib/datasource
      deploy:
        replicas: 1
    reference:
      image: lappsgrid/generic-datasource:latest
      ports:
        - 8081:8080
      volumes:
        - /var/lib/corora/BIONLP2016/bionlp-st-ge-2016-reference:/var/lib/datasource
      deploy:
        replicas: 1
    proteins:
      image: lappsgrid/generic-datasource:latest
      ports:
        - 8082:8080
      volumes:
        - /var/lib/corora/BIONLP2016/bionlp-st-ge-2016-test-proteins:/var/lib/datasource
      deploy:
        replicas: 1
    semeval:
      image: lappsgrid/generic-datasource:latest
      ports:
        - 8083:8080
      volumes:
        - /var/lib/corpora/SEMEVAL2017:/var/lib/datasource
      deploy:
        replicas: 1
    api:
      image: lappsgrid/api-service:latest
      ports:
        - 8084:8080
      secrets:
        - source: api.ini
          target: /etc/lapps/api.ini 
#      volumes:
#        - /etc/lapps:/etc/lapps
      deploy:
        replicas: 1
